version: "3.9"
name: autogpt
include:
  - supabase-compose.yml

#dependencies
services:
  postgres-server:
    container_name: postgre-sql-server
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=agpt_user
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=agpt_local
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    networks:
      - autogpt-network

  redis-cache:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes: 
      - cache:/data
    networks:
      - autogpt-network

# add autogpt backend and frontend services
  autogpt-backend:
    depends_on: 
      - redis-cache
    build:
      dockerfile: ./autogpt_platform/backend/backend.dockerfile
    environment:
      - SUPABASE_URL=http://kong:8000
      - SUPABASE_JWT_SECRET=your-super-secret-jwt-token-with-at-least-32-characters-long
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres?connect_timeout=60&schema=platform
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - ENABLE_AUTH=true
      - PYRO_HOST=0.0.0.0
      - EXECUTIONMANAGER_HOST=executor
      - FRONTEND_BASE_URL=http://localhost:3000
      - BACKEND_CORS_ALLOW_ORIGINS=["http://localhost:3000"]
    networks:
      - autogpt-network

networks:
     autogpt-network:
       driver: bridge

volumes:
  cache:
    driver: local